### ISSUE TITLE
Multiple adapters on single host

### ISSUE THREAD

**Issue by jpink** [mycontroller-org/serial2mqtt#2]
Hi!

I've two Arduinos connected via USB on ports `/dev/ttyACM0` and `/dev/ttyUSB0`. When I try to start second adapter (with different config) I got following error:
```
/usr/bin/java
java version: 1.8.0_181
Serial2mqtt is already running on pid[368]
```

The first adapter works and as a workaround I can use separate hosts or modify startup script.

**Comment by jkandasa** [comment]
@jpink good finding. When I design I thought we are going to use only one set of serial and MQTT, but now I understand that, we may have more than one.

I will change the design to support more than one set.

Yes, as a workaround, for now, you have to modify your startup script.

**Comment by jkandasa** [comment]
https://github.com/mycontroller-org/2mqtt supports multiple serial ports
